apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - image: yunosukedocker/demo-api:latest
          name: demo-api
          env:
            - name: DB_HOST
              value: mysql-server
            - name: DB_NAME
              value: demo
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: root_pass

---
apiVersion: v1
kind: Service
metadata:
  name: demo-api
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: demo-api
  type: NodePort
